# Importando librerias

In [23]:
import pandas as pd
import numpy as np
import os
import gc
import time

# Importando dataframe

In [2]:
full_path = "C:\Projects\EDA GSP"
df_path = os.path.join(full_path, "dataframes", "under_day_df.pkl")

In [3]:
# Load dataframe from the pickle file
df = pd.read_pickle(df_path)

In [4]:
pd.set_option('display.max_columns', None)

'page' la extraemos de NUMERICAL

In [5]:
df

,session_id,index,elapsed_time,event_name,name,level,page,room_coor_x,room_coor_y,screen_coor_x,screen_coor_y,hover_duration,text,fqid,room_fqid,text_fqid,fullscreen,hq,music,level_group,elapsed_time_log,time_diff,elapsed_time_diff_log,hover_duration_log
0,20090312431273200,0,0,cutscene_click,basic,0,NaN,-413.991394,-159.314682,380.0,494.0,NaN,undefined,intro,tunic.historicalsociety.closet,tunic.historicalsociety.closet.intro,0,0,1,0-4,0.0,0.0,0.0,NaN
1,20090312431273200,1,1323,person_click,basic,0,NaN,-413.991394,-159.314682,380.0,494.0,NaN,"Whatcha doing over there, Jo?",gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0,0,1,0-4,7.0,1323.0,7.0,NaN
2,20090312431273200,2,831,person_click,basic,0,NaN,-413.991394,-159.314682,380.0,494.0,NaN,Just talking to Teddy.,gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0,0,1,0-4,6.5,0.0,0.0,NaN
3,20090312431273200,3,1147,person_click,basic,0,NaN,-413.991394,-159.314682,380.0,494.0,NaN,I gotta run to my meeting!,gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0,0,1,0-4,7.0,316.0,6.0,NaN
4,20090312431273200,4,1863,person_click,basic,0,NaN,-412.991394,-159.314682,381.0,494.0,NaN,"Can I come, Gramps?",gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0,0,1,0-4,7.5,716.0,6.5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26296941,22100221145014656,1600,5483231,navigate_click,undefined,22,NaN,343.887299,36.701027,483.0,273.0,NaN,NaN,NaN,tunic.capitol_2.hall,NaN,0,0,1,13-22,15.5,1046.0,7.0,NaN
26296942,22100221145014656,1601,5485166,navigate_click,undefined,22,NaN,332.696075,141.493179,545.0,221.0,NaN,NaN,chap4_finale_c,tunic.capitol_2.hall,NaN,0,0,1,13-22,15.5,1935.0,7.5,NaN
26296943,22100221145014656,1602,5485917,navigate_click,undefined,22,NaN,369.912872,140.569199,611.0,217.0,NaN,NaN,NaN,tunic.capitol_2.hall,NaN,0,0,1,13-22,15.5,751.0,6.5,NaN
26296944,22100221145014656,1603,5486753,navigate_click,undefined,22,NaN,252.299652,123.805893,526.0,232.0,NaN,NaN,chap4_finale_c,tunic.capitol_2.hall,NaN,0,0,1,13-22,15.5,836.0,6.5,NaN
26296945,22100221145014656,1604,5487952,checkpoint,basic,22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chap4_finale_c,tunic.capitol_2.hall,NaN,0,0,1,13-22,15.5,1199.0,7.0,NaN

In [17]:
np.log(4586+8768)

9.499571244417814

In [16]:
np.log(4586) + np.log(8768)

17.509627472605647

In [6]:
df = df.drop("elapsed_time",axis=1)

In [7]:
df = df.drop("hover_duration",axis=1)

In [8]:
#df = df.drop("time_diff",axis=1)

In [16]:
df

,session_id,index,event_name,name,level,page,room_coor_x,room_coor_y,screen_coor_x,screen_coor_y,text,fqid,room_fqid,text_fqid,fullscreen,hq,music,level_group,elapsed_time_log,time_diff,elapsed_time_diff_log,hover_duration_log
0,20090312431273200,0,cutscene_click,basic,0,NaN,-413.991394,-159.314682,380.0,494.0,undefined,intro,tunic.historicalsociety.closet,tunic.historicalsociety.closet.intro,0,0,1,0-4,0.0,0.0,0.0,NaN
1,20090312431273200,1,person_click,basic,0,NaN,-413.991394,-159.314682,380.0,494.0,"Whatcha doing over there, Jo?",gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0,0,1,0-4,7.0,1323.0,7.0,NaN
2,20090312431273200,2,person_click,basic,0,NaN,-413.991394,-159.314682,380.0,494.0,Just talking to Teddy.,gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0,0,1,0-4,6.5,0.0,0.0,NaN
3,20090312431273200,3,person_click,basic,0,NaN,-413.991394,-159.314682,380.0,494.0,I gotta run to my meeting!,gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0,0,1,0-4,7.0,316.0,6.0,NaN
4,20090312431273200,4,person_click,basic,0,NaN,-412.991394,-159.314682,381.0,494.0,"Can I come, Gramps?",gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0,0,1,0-4,7.5,716.0,6.5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26296941,22100221145014656,1600,navigate_click,undefined,22,NaN,343.887299,36.701027,483.0,273.0,NaN,NaN,tunic.capitol_2.hall,NaN,0,0,1,13-22,15.5,1046.0,7.0,NaN
26296942,22100221145014656,1601,navigate_click,undefined,22,NaN,332.696075,141.493179,545.0,221.0,NaN,chap4_finale_c,tunic.capitol_2.hall,NaN,0,0,1,13-22,15.5,1935.0,7.5,NaN
26296943,22100221145014656,1602,navigate_click,undefined,22,NaN,369.912872,140.569199,611.0,217.0,NaN,NaN,tunic.capitol_2.hall,NaN,0,0,1,13-22,15.5,751.0,6.5,NaN
26296944,22100221145014656,1603,navigate_click,undefined,22,NaN,252.299652,123.805893,526.0,232.0,NaN,chap4_finale_c,tunic.capitol_2.hall,NaN,0,0,1,13-22,15.5,836.0,6.5,NaN
26296945,22100221145014656,1604,checkpoint,basic,22,NaN,NaN,NaN,NaN,NaN,NaN,chap4_finale_c,tunic.capitol_2.hall,NaN,0,0,1,13-22,15.5,1199.0,7.0,NaN

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 25542282 entries, 0 to 26296945
Data columns (total 21 columns):
 #   Column                 Dtype
---  ------                 -----
 0   session_id             int64
 1   index                  int64
 2   event_name             category
 3   name                   category
 4   level                  uint8
 5   page                   float64
 6   room_coor_x            float32
 7   room_coor_y            float32
 8   screen_coor_x          float32
 9   screen_coor_y          float32
 10  text                   category
 11  fqid                   category
 12  room_fqid              category
 13  text_fqid              category
 14  fullscreen             uint8
 15  hq                     uint8
 16  music                  uint8
 17  level_group            category
 18  elapsed_time_log       float16
 19  elapsed_time_diff_log  float16
 20  hover_duration_log     float16
dtypes: category(7), float16(3), float32(4), float64(1), int64(2), uint8(4)
memory usage: 1.6 GB

# Feature engineering para (level_group=0-4, Q=1)

In [8]:
CATEGORICAL = ['event_name', 'name','fqid', 'room_fqid', 'text_fqid', 'text']
NUMERICAL = ['elapsed_time','level','room_coor_x', 'room_coor_y', 'screen_coor_x', 'screen_coor_y', 'hover_duration', 'elapsed_time_log', 'time_diff', 'elapsed_time_diff_log']

In [9]:
categ = ['event_name', 'name','fqid', 'room_fqid', 'text_fqid', 'text']
numer = ["elapsed_time_log", "elapsed_time_diff_log", "hover_duration_log", 'room_coor_x', 'room_coor_y', 'screen_coor_x', 'screen_coor_y']
binary = ["fullscreen", "hq", "music"]

In [24]:
categ_1 = ['room_fqid']

## Categorical 80% selection

In [27]:
level_rooms = {}

In [15]:
session_number = len(df["session_id"].unique())
session_number

22936

In [ ]:
level_rooms = {}

for c in categ_1:
    # Compute the value counts for each group
    counts = df.groupby('level')[c].value_counts().sort_values(ascending=False).groupby(level=0)
    cumulative_counts = counts.cumsum()

    # Find the total count for each level
    totals = counts.sum()

    # Create a mask where the cumulative sum is less than or equal to 0.8 of total
    mask = cumulative_counts / totals <= 0.8

    # Filter the counts dataframe using the mask
    dominant_values = cumulative_counts[mask]

    # Store the dominant values in the level_rooms dictionary
    level_rooms[c] = {level: dominant_values.xs(level).index.tolist() for level in df['level'].unique()}

del counts, cumulative_counts, totals, mask, dominant_values

In [23]:
level_rooms

{'event_name': {0: ['navigate_click', 'person_click'],
  1: ['cutscene_click'],
  2: ['navigate_click', 'cutscene_click', 'person_click'],
  3: ['navigate_click', 'object_click'],
  4: ['navigate_click'],
  5: ['navigate_click'],
  6: ['person_click'],
  7: ['navigate_click', 'person_click'],
  8: ['person_click', 'navigate_click'],
  9: ['navigate_click', 'person_click', 'object_click'],
  10: ['person_click', 'navigate_click'],
  11: ['navigate_click', 'person_click', 'object_click'],
  12: ['navigate_click', 'map_hover'],
  13: ['cutscene_click'],
  14: ['navigate_click'],
  15: ['navigate_click', 'person_click'],
  16: ['cutscene_click'],
  17: ['navigate_click', 'person_click'],
  18: ['navigate_click'],
  19: ['navigate_click'],
  20: ['navigate_click', 'object_click', 'person_click'],
  21: ['navigate_click', 'person_click', 'object_click'],
  22: ['navigate_click', 'map_hover']}}

## FE

In [10]:
unique_sessions = df['session_id'].unique()
np.random.seed(22)
random_sessions = np.random.choice(unique_sessions, size=int(0.5 * len(unique_sessions)), replace=False)
sampled_df = df[df['session_id'].isin(random_sessions)]

In [11]:
sampled_df_0_4 = sampled_df[sampled_df['level_group'] == '0-4'].copy()

In [12]:
sampled_df_0_4.shape

(1943173, 22)

In [63]:
df.shape

(25542282, 22)

In [13]:
# Define number of quantiles
n_quantiles = 4

# Define a function to compute quantiles within each group
def compute_quantiles(group):
    group['quantile'] = pd.qcut(group['index'], n_quantiles, labels=False, duplicates='drop')
    return group

In [56]:
def apply_quantiles(df):
    df_quantiles = df.groupby(["session_id", "level"]).apply(compute_quantiles)
    df_quantiles = df_quantiles.reset_index(drop=True)
    return df_quantiles

In [58]:
df_quantiles = apply_quantiles(df)

In [ ]:
df_0_4 = df[df['level_group'] == '0-4'].copy()
df_5_12 = df[df['level_group'] == '5-12'].copy()
df_13_22 = df[df['level_group'] == '13-22'].copy()
del df
gc.collect()

def feature_engineer(dataset_df):
    start_time = time.time()
    
    binary_groups = [] 
    for c in binary:
        tmp_binary_mean = dataset_df.groupby("session_id")[c].mean()
        binary_groups.append(tmp_binary_mean)

    print("Binary Completado. Tiempo transcurrido: {:.2f} segundos".format(time.time() - start_time))
    print()

    groups = []
    
    # Calculating the total elapsed time for each session, level and quantile, transforming with log and adding 1
    elapsed_time = dataset_df.groupby(["session_id", "level", "quantile"])["time_diff"].sum()
    elapsed_time_log = np.log1p(elapsed_time) # apply log transformation and add 1
    elapsed_time_log.name = "quantile_elapsed"
    groups.append(elapsed_time_log)
    dataset_df = dataset_df.drop("time_diff",axis=1)

    del elapsed_time # release memory
    gc.collect() # collect garbage

    print("Elapsed Time por quantil Completado. Tiempo transcurrido: {:.2f} segundos".format(time.time() - start_time))
    print()

    # Counting the number of events for each session, level and quantile
    event_count = dataset_df.groupby(["session_id", "level", "quantile"])["index"].count()
    event_count.name = "session_events"
    groups.append(event_count)

    print("Eventos por quantil Completado. Tiempo transcurrido: {:.2f} segundos".format(time.time() - start_time))
    print()

    # Calculate the event density for each session, level and quantile
    event_density = np.where(elapsed_time_log > 0, event_count / elapsed_time_log, 0)
    # event_density = pd.Series(event_density, name='event_density')
    event_density = pd.Series(np.where(elapsed_time_log > 0, event_count / elapsed_time_log, 0), index=elapsed_time_log.index, name='event_density')
    groups.append(event_density)

    print("Densidad de eventos Completado. Tiempo transcurrido: {:.2f} segundos".format(time.time() - start_time))
    print()

    del event_count, event_density # release memory
    gc.collect() # collect garbage

    for c in numer:
        if c == "hover_duration_log" or c == "page":
            tmp_mean = dataset_df.groupby(["session_id", "level", "quantile"])[c].mean()
            tmp_mean = tmp_mean.fillna(-1 if c == "page" else 0)
            tmp_std = dataset_df.groupby(["session_id", "level", "quantile"])[c].std(ddof=0)
            tmp_std = tmp_std.fillna(-1 if c == "page" else 0)  # fill NaN with -1 for 'page', 0 for others
            tmp_std.name = tmp_std.name + '_std'
            groups.append(tmp_mean)
            groups.append(tmp_std)

            del tmp_mean, tmp_std # release memory
            gc.collect() # collect garbage
        else:
            tmp_mean = dataset_df.groupby(["session_id", "level", "quantile"])[c].mean()
            tmp_std =  dataset_df.groupby(["session_id", "level", "quantile"])[c].std(ddof=0)
            tmp_std.name = tmp_std.name + '_std'
            groups.append(tmp_mean)
            groups.append(tmp_std)
            del tmp_mean, tmp_std # release memory
            gc.collect() # collect garbage

        print(f"{c} Completado. Tiempo transcurrido: {time.time() - start_time:.2f} segundos")
        print()

    for c in categ: 
        tmp_cat = dataset_df.groupby(["session_id", "level", "quantile"])[c].agg("nunique")
        groups.append(tmp_cat)
        del tmp_cat # release memory
        gc.collect() # collect garbage
        print(f"{c} Completado. Tiempo transcurrido: {time.time() - start_time:.2f} segundos")
        print()
    df_unstacked = pd.concat(groups, axis=1).unstack(['level',"quantile"])
    df_unstacked.columns = ['_'.join(map(str, col)).rstrip('_') for col in df_unstacked.columns.values]

    print("Unstack Completado. Tiempo transcurrido: {:.2f} segundos".format(time.time() - start_time))
    print()

    del groups # release memory
    gc.collect() # collect garbage

    df_binary = pd.concat(binary_groups, axis=1)
    df_binary.columns = binary

    print("Binary concatenado Completado. Tiempo transcurrido: {:.2f} segundos".format(time.time() - start_time))
    print()

    del binary_groups # release memory
    gc.collect() # collect garbage

    df_final = pd.merge(df_unstacked, df_binary, left_index=True, right_index=True)

    print("Merge Completado. Tiempo transcurrido: {:.2f} segundos".format(time.time() - start_time))
    print()

    del df_unstacked, df_binary # release memory
    gc.collect() # collect garbage

    df_final = df_final.fillna(-1)

    return df_final

df_1 = feature_engineer(df_0_4)
df_2 = feature_engineer(df_5_12)
df_3 = feature_engineer(df_13_22)
del df_0_4, df_5_12, df_13_22
gc.collect()

In [59]:
full_path

'C:\\Projects\\EDA GSP'

In [60]:
# Define the output directory and file
output_dir = os.path.join(full_path, 'dataframes')
if not os.path.exists(output_dir):  # create the directory if it doesn't exist
    os.makedirs(output_dir)
output_file = os.path.join(output_dir, 'df_quantiles.pkl')
# Save dataframe to pickle file
df_quantiles.to_pickle(output_file)

In [62]:
df_quantiles["quantile"]

count    2.554228e+07
mean     1.489684e+00
std      1.127214e+00
min      0.000000e+00
25%      0.000000e+00
50%      1.000000e+00
75%      3.000000e+00
max      3.000000e+00
Name: quantile, dtype: float64

In [65]:
def feature_engineer(dataset_df):
    start_time = time.time()
    
    binary_groups = [] 
    for c in binary:
        tmp_binary_mean = dataset_df.groupby("session_id")[c].mean()
        binary_groups.append(tmp_binary_mean)

    print("Binary Completado. Tiempo transcurrido: {:.2f} segundos".format(time.time() - start_time))
    print()

    groups = []
    
    # Calculating the total elapsed time for each session, level and quantile, transforming with log and adding 1
    elapsed_time = dataset_df.groupby(["session_id", "level", "quantile"])["time_diff"].sum()
    elapsed_time_log = np.log1p(elapsed_time) # apply log transformation and add 1
    elapsed_time_log.name = "quantile_elapsed"
    groups.append(elapsed_time_log)
    dataset_df = dataset_df.drop("time_diff",axis=1)

    del elapsed_time # release memory
    gc.collect() # collect garbage

    print("Elapsed Time por quantil Completado. Tiempo transcurrido: {:.2f} segundos".format(time.time() - start_time))
    print()

    # Counting the number of events for each session, level and quantile
    event_count = dataset_df.groupby(["session_id", "level", "quantile"])["index"].count()
    event_count.name = "session_events"
    groups.append(event_count)

    print("Eventos por quantil Completado. Tiempo transcurrido: {:.2f} segundos".format(time.time() - start_time))
    print()

    # Calculate the event density for each session, level and quantile
    event_density = np.where(elapsed_time_log > 0, event_count / elapsed_time_log, 0)
    # event_density = pd.Series(event_density, name='event_density')
    event_density = pd.Series(np.where(elapsed_time_log > 0, event_count / elapsed_time_log, 0), index=elapsed_time_log.index, name='event_density')
    groups.append(event_density)

    print("Densidad de eventos Completado. Tiempo transcurrido: {:.2f} segundos".format(time.time() - start_time))
    print()

    del event_count, event_density # release memory
    gc.collect() # collect garbage

    for c in numer:
        if c == "hover_duration_log" or c == "page":
            tmp_mean = dataset_df.groupby(["session_id", "level", "quantile"])[c].mean()
            tmp_mean = tmp_mean.fillna(-1 if c == "page" else 0)
            tmp_std = dataset_df.groupby(["session_id", "level", "quantile"])[c].std(ddof=0)
            tmp_std = tmp_std.fillna(-1 if c == "page" else 0)  # fill NaN with -1 for 'page', 0 for others
            tmp_std.name = tmp_std.name + '_std'
            groups.append(tmp_mean)
            groups.append(tmp_std)

            del tmp_mean, tmp_std # release memory
            gc.collect() # collect garbage
        else:
            tmp_mean = dataset_df.groupby(["session_id", "level", "quantile"])[c].mean()
            tmp_std =  dataset_df.groupby(["session_id", "level", "quantile"])[c].std(ddof=0)
            tmp_std.name = tmp_std.name + '_std'
            groups.append(tmp_mean)
            groups.append(tmp_std)
            del tmp_mean, tmp_std # release memory
            gc.collect() # collect garbage

        print(f"{c} Completado. Tiempo transcurrido: {time.time() - start_time:.2f} segundos")
        print()

    for c in categ: 
        tmp_cat = dataset_df.groupby(["session_id", "level", "quantile"])[c].agg("nunique")
        groups.append(tmp_cat)
        del tmp_cat # release memory
        gc.collect() # collect garbage
        print(f"{c} Completado. Tiempo transcurrido: {time.time() - start_time:.2f} segundos")
        print()
    df_unstacked = pd.concat(groups, axis=1).unstack(['level',"quantile"])
    df_unstacked.columns = ['_'.join(map(str, col)).rstrip('_') for col in df_unstacked.columns.values]

    print("Unstack Completado. Tiempo transcurrido: {:.2f} segundos".format(time.time() - start_time))
    print()

    del groups # release memory
    gc.collect() # collect garbage

    df_binary = pd.concat(binary_groups, axis=1)
    df_binary.columns = binary

    print("Binary concatenado Completado. Tiempo transcurrido: {:.2f} segundos".format(time.time() - start_time))
    print()

    del binary_groups # release memory
    gc.collect() # collect garbage

    df_final = pd.merge(df_unstacked, df_binary, left_index=True, right_index=True)

    print("Merge Completado. Tiempo transcurrido: {:.2f} segundos".format(time.time() - start_time))
    print()

    del df_unstacked, df_binary # release memory
    gc.collect() # collect garbage

    df_final = df_final.fillna(-1)

    return df_final

Para calcular los quantiles cogemos "index" para poder distribuirlo en 4 partes iguales por nivel.

In [18]:
dfs_prueba=[]
# Apply the function to compute quantiles within each 'session_id' and 'level'
sampled_df_0_4_group = sampled_df_0_4.groupby(["session_id", "level"]).apply(compute_quantiles)
sampled_df_0_4_group = sampled_df_0_4_group.reset_index(drop=True)
sampled_df_0_4_group

,session_id,index,event_name,name,level,page,room_coor_x,room_coor_y,screen_coor_x,screen_coor_y,text,fqid,room_fqid,text_fqid,fullscreen,hq,music,level_group,elapsed_time_log,elapsed_time_diff_log,hover_duration_log,quantile
0,20090312431273200,0,cutscene_click,basic,0,NaN,-413.991394,-159.314682,380.0,494.0,undefined,intro,tunic.historicalsociety.closet,tunic.historicalsociety.closet.intro,0,0,1,0-4,0.0,0.0,NaN,0
1,20090312431273200,1,person_click,basic,0,NaN,-413.991394,-159.314682,380.0,494.0,"Whatcha doing over there, Jo?",gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0,0,1,0-4,7.0,7.0,NaN,0
2,20090312431273200,2,person_click,basic,0,NaN,-413.991394,-159.314682,380.0,494.0,Just talking to Teddy.,gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0,0,1,0-4,6.5,0.0,NaN,0
3,20090312431273200,3,person_click,basic,0,NaN,-413.991394,-159.314682,380.0,494.0,I gotta run to my meeting!,gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0,0,1,0-4,7.0,6.0,NaN,0
4,20090312431273200,4,person_click,basic,0,NaN,-412.991394,-159.314682,381.0,494.0,"Can I come, Gramps?",gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0,0,1,0-4,7.5,6.5,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1943168,22100215460321130,144,map_hover,basic,4,NaN,NaN,NaN,NaN,NaN,NaN,toentry,tunic.kohlcenter.halloffame,NaN,0,0,1,0-4,12.5,7.0,6.0,2
1943169,22100215460321130,145,map_hover,basic,4,NaN,NaN,NaN,NaN,NaN,NaN,tunic.kohlcenter,tunic.kohlcenter.halloffame,NaN,0,0,1,0-4,12.5,0.0,3.0,3
1943170,22100215460321130,146,map_click,undefined,4,NaN,-551.213196,51.957447,482.0,297.0,NaN,tunic.capitol_0,tunic.kohlcenter.halloffame,NaN,0,0,1,0-4,12.5,7.0,NaN,3
1943171,22100215460321130,147,navigate_click,undefined,4,NaN,-3.533728,44.663631,271.0,286.0,NaN,chap1_finale,tunic.capitol_0.hall,NaN,0,0,1,0-4,12.5,8.0,NaN,3
1943172,22100215460321130,148,checkpoint,basic,4,NaN,NaN,NaN,NaN,NaN,NaN,chap1_finale_c,tunic.capitol_0.hall,NaN,0,0,1,0-4,13.0,11.0,NaN,3

In [19]:
sampled_df_0_4_group["quantile"].info()

<class 'pandas.core.series.Series'>
RangeIndex: 1943173 entries, 0 to 1943172
Series name: quantile
Non-Null Count    Dtype
--------------    -----
1943173 non-null  int64
dtypes: int64(1)
memory usage: 14.8 MB

## Num feature engineering "elapse_time_log"

In [20]:
# Group by 'session_id', 'level', and 'quantile' and compute the mean of 'time_diff'
grouped = sampled_df_0_4_group.groupby(["session_id", "level", "quantile"])["elapsed_time_diff_log"].mean()
dfs_prueba.append(grouped)
dataset_df_prueba = pd.concat(dfs_prueba,axis=1)

In [21]:
dataset_df_prueba.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 229360 entries, (20090312431273200, 0, 0) to (22100215460321130, 4, 3)
Data columns (total 1 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   elapsed_time_diff_log  229360 non-null  float32
dtypes: float32(1)
memory usage: 1.8 MB

In [22]:
dataset_df_prueba

                                  elapsed_time_diff_log
session_id        level quantile
20090312431273200 0     0                      4.928571
                        1                      7.000000
                        2                      6.785714
                        3                      6.785714
                  1     0                      6.312500
...                                                 ...
22100215460321130 3     3                      7.125000
                  4     0                      7.125000
                        1                      6.625000
                        2                      5.375000
                        3                      6.500000

[229360 rows x 1 columns]

In [23]:
df_unstacked = dataset_df_prueba.unstack(['level',"quantile"])

In [25]:
df_unstacked.columns = ['_'.join(map(str, col)).rstrip('_') for col in df_unstacked.columns.values]

In [ ]:
df_unstacked.isna().sum()

In [45]:
df_page = []
grouped_page = sampled_df_0_4_group.groupby(["session_id", "level", "quantile"])["page"].mean()
df_page.append(grouped_page)
dataset_df_page = pd.concat(df_page,axis=1)

In [46]:
dataset_df_page

                                  page
session_id        level quantile
20090312431273200 0     0          NaN
                        1          NaN
                        2          NaN
                        3          NaN
                  1     0          NaN
...                                ...
22100215460321130 3     3          NaN
                  4     0          1.0
                        1          NaN
                        2          NaN
                        3          NaN

[229360 rows x 1 columns]

In [47]:
df_unstacked_page = dataset_df_page.unstack(['level',"quantile"])
df_unstacked_page

                  page
level                0                1                2                 3
quantile             0   1   2   3    0   1   2   3    0   1    2   3    0
session_id
20090312431273200  NaN NaN NaN NaN  NaN NaN NaN NaN  NaN NaN  NaN NaN  NaN  \
20090312455206810  NaN NaN NaN NaN  NaN NaN NaN NaN  NaN NaN  NaN NaN  NaN
20090313571836404  NaN NaN NaN NaN  NaN NaN NaN NaN  0.0 NaN  0.0 NaN  NaN
20090314363702160  NaN NaN NaN NaN  NaN NaN NaN NaN  NaN NaN  NaN NaN  NaN
20090315081004164  NaN NaN NaN NaN  NaN NaN NaN NaN  NaN NaN  NaN NaN  NaN
...                ...  ..  ..  ..  ...  ..  ..  ..  ...  ..  ...  ..  ...
22100213081672770  NaN NaN NaN NaN  NaN NaN NaN NaN  0.0 NaN  NaN NaN  NaN
22100215032067016  NaN NaN NaN NaN  NaN NaN NaN NaN  NaN NaN  NaN NaN  NaN
22100215190998610  NaN NaN NaN NaN  NaN NaN NaN NaN  NaN NaN  NaN NaN  NaN
22100215241104530  NaN NaN NaN NaN  NaN NaN NaN NaN  NaN NaN  NaN NaN  NaN
22100215460321130  NaN NaN NaN NaN  0.0 NaN NaN NaN  NaN NaN  NaN NaN  0.0


level                             4
quantile            1    2   3    0   1   2   3
session_id
20090312431273200 NaN  NaN NaN  NaN NaN NaN NaN
20090312455206810 NaN  NaN NaN  NaN NaN NaN NaN
20090313571836404 NaN  NaN NaN  NaN NaN NaN NaN
20090314363702160 NaN  NaN NaN  NaN NaN NaN NaN
20090315081004164 NaN  NaN NaN  NaN NaN NaN NaN
...                ..  ...  ..  ...  ..  ..  ..
22100213081672770 NaN  NaN NaN  NaN NaN NaN NaN
22100215032067016 NaN  NaN NaN  NaN NaN NaN NaN
22100215190998610 NaN  NaN NaN  NaN NaN NaN NaN
22100215241104530 NaN  0.0 NaN  1.0 NaN NaN NaN
22100215460321130 NaN  NaN NaN  1.0 NaN NaN NaN

[11468 rows x 20 columns]

### STD FE

In [ ]:
dfs_std_fe = []

In [ ]:
# Std antes, esto devuelve valores NaN si solo recibe 1 input.
# grouped_std = sampled_df_0_4_group.groupby(["session_id", "level", "quantile"])["elapsed_time_diff_log"].agg("std")

In [ ]:
grouped_std = sampled_df_0_4_group.groupby(["session_id", "level", "quantile"])["elapsed_time_diff_log"].std(ddof=0)

In [ ]:
dfs_std_fe.append(grouped_std)
dataset_dfs_std_fe = pd.concat(dfs_std_fe,axis=1)

In [ ]:
dataset_dfs_std_fe

In [ ]:
df_unstacked_std = dataset_dfs_std_fe.unstack(['level',"quantile"])

In [ ]:
df_unstacked_std.isna().sum()

## Feature engineering hover_duration_log

In [ ]:
dfs_hdl_fe = []
grouped_hdl = sampled_df_0_4_group.groupby(["session_id", "level", "quantile"])["hover_duration_log"].mean()
grouped_hdl = grouped_hdl.fillna(0)
dfs_hdl_fe.append(grouped_hdl)
dataset_hdl = pd.concat(dfs_hdl_fe,axis=1)

In [ ]:
dataset_hdl

In [ ]:
df_unstacked_hdl = dataset_hdl.unstack(['level',"quantile"])
df_unstacked_hdl

In [ ]:
df_unstacked_hdl.info()

In [ ]:
df_unstacked_hdl.isna().sum()

In [ ]:
dfs_hdl_fe_std = []
grouped_hdl_std = sampled_df_0_4_group.groupby(["session_id", "level", "quantile"])["hover_duration_log"].std(ddof=0)

In [ ]:
grouped_hdl_std = grouped_hdl_std.fillna(0)

In [ ]:
dfs_hdl_fe_std.append(grouped_hdl_std)
dataset_hdl_std = pd.concat(dfs_hdl_fe_std,axis=1)

In [ ]:
dataset_hdl_std

In [ ]:
df_unstacked_hdl = dataset_hdl_std.unstack(['level',"quantile"])
df_unstacked_hdl

## Cat feature engineering

### Text

In [ ]:
dfs_cat_fe = []

In [ ]:
grouped_cat = sampled_df_0_4_group.groupby(["session_id", "level", "quantile"])["text"].agg("nunique")

In [ ]:
dfs_cat_fe.append(grouped_cat)
dataset_dfs_cat_fe = pd.concat(dfs_cat_fe,axis=1)

In [ ]:
dataset_dfs_cat_fe

In [ ]:
df_unstacked_cat = dataset_dfs_cat_fe.unstack(['level',"quantile"])

In [ ]:
df_unstacked_cat

In [ ]:
df_unstacked_cat.isna().sum()

### Binary categ

In [32]:
binary

['fullscreen', 'hq', 'music']

In [31]:
sampled_df_0_4_group["fullscreen"] = sampled_df_0_4_group["fullscreen"].astype("uint8")

In [33]:
sampled_df_0_4_group["hq"] = sampled_df_0_4_group["hq"].astype("uint8")

In [34]:
sampled_df_0_4_group["music"] = sampled_df_0_4_group["music"].astype("uint8")

In [41]:
dfs_bin_fe = []

In [42]:
grouped_bin = sampled_df_0_4_group.groupby("session_id")["fullscreen"].mean()

In [43]:
dfs_bin_fe.append(grouped_bin)
dataset_dfs_bin_fe = pd.concat(dfs_bin_fe,axis=1)

In [44]:
dataset_dfs_bin_fe

                   fullscreen
session_id
20090312431273200         0.0
20090312455206810         1.0
20090313571836404         0.0
20090314363702160         0.0
20090315081004164         0.0
...                       ...
22100213081672770         0.0
22100215032067016         0.0
22100215190998610         0.0
22100215241104530         0.0
22100215460321130         0.0

[11468 rows x 1 columns]

# DF FINAL

In [66]:
df_nuevo = feature_engineer(df_quantiles)

Binary Completado. Tiempo transcurrido: 1.93 segundos

Elapsed Time por quantil Completado. Tiempo transcurrido: 35.72 segundos

Eventos por quantil Completado. Tiempo transcurrido: 38.20 segundos

Densidad de eventos Completado. Tiempo transcurrido: 38.49 segundos

elapsed_time_log Completado. Tiempo transcurrido: 44.29 segundos

elapsed_time_diff_log Completado. Tiempo transcurrido: 49.66 segundos

hover_duration_log Completado. Tiempo transcurrido: 54.91 segundos

room_coor_x Completado. Tiempo transcurrido: 59.99 segundos

room_coor_y Completado. Tiempo transcurrido: 65.13 segundos

screen_coor_x Completado. Tiempo transcurrido: 70.23 segundos

screen_coor_y Completado. Tiempo transcurrido: 75.36 segundos

event_name Completado. Tiempo transcurrido: 80.28 segundos

name Completado. Tiempo transcurrido: 84.65 segundos

fqid Completado. Tiempo transcurrido: 90.34 segundos

room_fqid Completado. Tiempo transcurrido: 95.32 segundos

text_fqid Completado. Tiempo transcurrido: 100.11 segundos

text Completado. Tiempo transcurrido: 105.14 segundos

Unstack Completado. Tiempo transcurrido: 112.53 segundos

Binary concatenado Completado. Tiempo transcurrido: 112.96 segundos

Merge Completado. Tiempo transcurrido: 113.42 segundos

In [84]:
df_nuevo = df_nuevo.fillna(-1)

In [88]:
df_nuevo.info()

<class 'pandas.core.frame.DataFrame'>
Index: 22936 entries, 20090312431273200 to 22100221145014656
Columns: 2119 entries, quantile_elapsed_0_0 to music
dtypes: float32(644), float64(1475)
memory usage: 315.1 MB

In [85]:
df_nuevo.isna().sum().sum()

0

In [18]:
df_0_4 = df[df['level_group'] == '0-4'].copy()
df_5_12 = df[df['level_group'] == '5-12'].copy()
df_13_22 = df[df['level_group'] == '13-22'].copy()

In [31]:
groups_1, binary_groups_1 = feature_engineer(df_0_4)

Binary Completado. Tiempo transcurrido: 0.39 segundos

Quantiles Completado. Tiempo transcurrido: 193.51 segundos

Elapsed Time por quantil Completado. Tiempo transcurrido: 194.01 segundos

Eventos por quantil Completado. Tiempo transcurrido: 194.35 segundos

Densidad de eventos Completado. Tiempo transcurrido: 194.38 segundos

elapsed_time_log Completado. Tiempo transcurrido: 195.19 segundos

elapsed_time_diff_log Completado. Tiempo transcurrido: 196.01 segundos

hover_duration_log Completado. Tiempo transcurrido: 196.81 segundos

room_coor_x Completado. Tiempo transcurrido: 197.57 segundos

room_coor_y Completado. Tiempo transcurrido: 198.33 segundos

screen_coor_x Completado. Tiempo transcurrido: 199.09 segundos

screen_coor_y Completado. Tiempo transcurrido: 199.86 segundos

event_name Completado. Tiempo transcurrido: 200.53 segundos

name Completado. Tiempo transcurrido: 201.17 segundos

fqid Completado. Tiempo transcurrido: 201.89 segundos

room_fqid Completado. Tiempo transcurrido: 202.52 segundos

text_fqid Completado. Tiempo transcurrido: 203.15 segundos

text Completado. Tiempo transcurrido: 203.83 segundos

In [33]:
df_prueba_1 = pd.concat(groups_1, axis=1)

NotImplementedError: Can only union MultiIndex with MultiIndex or Index of tuples, try mi.to_flat_index().union(other) instead.

In [37]:
groups_1[0]

session_id         level  quantile
20090312431273200  0      0            8.646466
                          1            8.966229
                          2            8.756368
                          3            8.762020
                   1      0            9.373054
                                        ...
22100221145014656  3      3           10.508459
                   4      0            7.912423
                          1            8.559486
                          2            7.234898
                          3           11.323616
Name: time_diff, Length: 458720, dtype: float64

In [44]:
groups_1[0].index

MultiIndex([(20090312431273200, 0, 0),
            (20090312431273200, 0, 1),
            (20090312431273200, 0, 2),
            (20090312431273200, 0, 3),
            (20090312431273200, 1, 0),
            (20090312431273200, 1, 1),
            (20090312431273200, 1, 2),
            (20090312431273200, 1, 3),
            (20090312431273200, 2, 0),
            (20090312431273200, 2, 1),
            ...
            (22100221145014656, 2, 2),
            (22100221145014656, 2, 3),
            (22100221145014656, 3, 0),
            (22100221145014656, 3, 1),
            (22100221145014656, 3, 2),
            (22100221145014656, 3, 3),
            (22100221145014656, 4, 0),
            (22100221145014656, 4, 1),
            (22100221145014656, 4, 2),
            (22100221145014656, 4, 3)],
           names=['session_id', 'level', 'quantile'], length=458720)

In [38]:
len(groups_1)

23

In [49]:
for i,c in enumerate(groups_1):
    print(c.index.names)
    print(i)
    print()

['session_id', 'level', 'quantile']
0

['session_id', 'level', 'quantile']
1

[None]
2

['session_id', 'level', 'quantile']
3

['session_id', 'level', 'quantile']
4

['session_id', 'level', 'quantile']
5

['session_id', 'level', 'quantile']
6

['session_id', 'level', 'quantile']
7

['session_id', 'level', 'quantile']
8

['session_id', 'level', 'quantile']
9

['session_id', 'level', 'quantile']
10

['session_id', 'level', 'quantile']
11

['session_id', 'level', 'quantile']
12

['session_id', 'level', 'quantile']
13

['session_id', 'level', 'quantile']
14

['session_id', 'level', 'quantile']
15

['session_id', 'level', 'quantile']
16

['session_id', 'level', 'quantile']
17

['session_id', 'level', 'quantile']
18

['session_id', 'level', 'quantile']
19

['session_id', 'level', 'quantile']
20

['session_id', 'level', 'quantile']
21

['session_id', 'level', 'quantile']
22

In [50]:
groups_1[2]

0         0.809579
1         0.780707
2         0.799418
3         0.798903
4         0.853510
            ...
458715    1.808067
458716    0.631918
458717    0.584147
458718    0.691095
458719    0.441555
Name: event_density, Length: 458720, dtype: float64

In [47]:
groups_1[1].index.names

FrozenList(['session_id', 'level', 'quantile'])

In [51]:
groups_1[1]

session_id         level  quantile
20090312431273200  0      0            7
                          1            7
                          2            7
                          3            7
                   1      0            8
                                      ..
22100221145014656  3      3           19
                   4      0            5
                          1            5
                          2            5
                          3            5
Name: index, Length: 458720, dtype: int64

In [53]:
groups_2, binary_groups_2 = feature_engineer(df_0_4)

Binary Completado. Tiempo transcurrido: 0.40 segundos

Quantiles Completado. Tiempo transcurrido: 192.37 segundos

Elapsed Time por quantil Completado. Tiempo transcurrido: 192.86 segundos

Eventos por quantil Completado. Tiempo transcurrido: 193.22 segundos

Densidad de eventos Completado. Tiempo transcurrido: 193.28 segundos

elapsed_time_log Completado. Tiempo transcurrido: 194.08 segundos

elapsed_time_diff_log Completado. Tiempo transcurrido: 194.86 segundos

hover_duration_log Completado. Tiempo transcurrido: 195.64 segundos

room_coor_x Completado. Tiempo transcurrido: 196.41 segundos

room_coor_y Completado. Tiempo transcurrido: 197.18 segundos

screen_coor_x Completado. Tiempo transcurrido: 197.94 segundos

screen_coor_y Completado. Tiempo transcurrido: 198.71 segundos

event_name Completado. Tiempo transcurrido: 199.39 segundos

name Completado. Tiempo transcurrido: 200.00 segundos

fqid Completado. Tiempo transcurrido: 200.72 segundos

room_fqid Completado. Tiempo transcurrido: 201.36 segundos

text_fqid Completado. Tiempo transcurrido: 202.00 segundos

text Completado. Tiempo transcurrido: 202.69 segundos

In [54]:
groups_2[2]

session_id         level  quantile
20090312431273200  0      0           0.809579
                          1           0.780707
                          2           0.799418
                          3           0.798903
                   1      0           0.853510
                                        ...
22100221145014656  3      3           1.808067
                   4      0           0.631918
                          1           0.584147
                          2           0.691095
                          3           0.441555
Name: event_density, Length: 458720, dtype: float64

In [55]:
df_prueba_2 = pd.concat(groups_2,axis=1)

In [ ]:
group_dic = {"0-4":[0,1,2,3,4],"5-12":[5,6,7,8,9,10,11,12],"13-22":[13,14,15,16,17,18,19,20,21,22]}